feat: deploy to staging finish

diff --git a/.github/workflows/cd-main.yml b/.github/workflows/cd-main.yml
--- a/.github/workflows/cd-main.yml
+++ b/.github/workflows/cd-main.yml
@@ -13,29 +13,29 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  # verificar-rama-origen:
-  #   name: Verificar que el Tag esté en Main
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout del código
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #
-  #     - name: Validar si el commit pertenece a la rama main
-  #       run: |
-  #         echo "🔍 Analizando el commit asociado al tag..."
-  #         git fetch origin main
-  #         if git branch -r --contains ${{ github.sha }} | grep -q "origin/main"; then
-  #           echo "✅ PASS: El tag fue creado sobre un commit de la rama main."
-  #         else
-  #           echo "❌ ERROR: El tag no pertenece a la rama main. El despliegue se cancela."
-  #           exit 1
-  #         fi
+  verificar-rama-origen:
+    name: Verificar que el Tag esté en Main
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout del código
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Validar si el commit pertenece a la rama main
+        run: |
+          echo "🔍 Analizando el commit asociado al tag..."
+          git fetch origin main
+          if git branch -r --contains ${{ github.sha }} | grep -q "origin/main"; then
+            echo "✅ PASS: El tag fue creado sobre un commit de la rama main."
+          else
+            echo "❌ ERROR: El tag no pertenece a la rama main. El despliegue se cancela."
+            exit 1
+          fi
 
   entrega-build-and-push:
     name: Construir y Subir Imágenes
-    # needs: verificar-rama-origen
+    needs: verificar-rama-origen
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -93,22 +93,3 @@ jobs:
           echo "Levantando Staging en puertos secundarios..."
           docker compose pull
           docker compose -p staging up -d
-
-  despliegue-produccion:
-    name: Despliegue a Producción
-    needs: despliegue-staging
-    environment: production
-    runs-on: self-hosted
-    steps:
-      - name: Descargar repositorio
-        uses: actions/checkout@v4
-
-      - name: Levantar Producción
-        env:
-          PORT_BACKEND: ${{ vars.PORT_BACKEND }}
-          PORT_BFF: ${{ vars.PORT_BFF }}
-          PORT_FRONTEND: ${{ vars.PORT_FRONTEND }}
-        run: |
-          echo "Levantando Producción..."
-          docker compose pull
-          docker compose -p prod up -d
